[Unit]
Requires=asrock-nct6686.service
After=asrock-nct6686.service

[Service]
Environment="CC_PORT=11987"
Environment="CC_HOST_IP4=127.0.0.1"
Environment="CC_HOST_IP6=::1"
ExecStopPost=/usr/local/libexec/asrock-nct6686/restore-bios.sh
